[build]
  publish = "."                   # Directorio que contiene tu index.php
  command = "composer install"    # Si estás usando Composer para gestionar dependencias

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200