[build]
  publish = "build" # Reemplaza con el directorio donde se encuentra tu index.html
  command = "npm run build" # Reemplaza con tu comando de construcción

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200